apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnfs-csi-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnfs-csi-controller
  template:
    metadata:
      labels:
        app: cnfs-csi-controller
    spec:
      serviceAccountName: cnfs-csi-controller-sa
      containers:
        #CSI controller plugin
        - name: cnfs-csi-controller
          image: cnfs-csi-driver:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(NODE_ID)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          volumeMounts:
            - name: socket-dir
              mountPath: /csi

        #External provisioner sidecar
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.0.1
          args:
            - "--csi-address=/csi/csi.sock"
            - "--feature-gates=Topology=true"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
